### ISSUE TITLE
Importing multiple modules and using them in the same callback

### ISSUE THREAD

**Issue by mawkler** [miversen33/import.nvim#11]
Is there any way to import multiple modules and use them in the same callback function? What I intend is to do something like this:

```lua
import({'module1', 'module2'}, function(module1, module2)
  module1.foo(module2.bar())
end)
```

**Comment by miversen33** [comment]
That is an interesting use case.

No, currently that behavior is not supported. I'll have to have a think about if I want to add that kind of support. 

What would you expect to happen if there is an error importing any of the modules in the table?

**Comment by mawkler** [comment]
@miversen33 Since the code in the callback requires both the modules it makes sense to me that `import()` only calls the callback if every module was succesfully imported, but it could mark their `ImportStatus` individually. For instance, if `module1` exists but `module2` doesn't, don't call the callback and set `module1.imported = true` and `module2.imported = false`.

Alternatively, `import()` could set the input parameter to the callback function to `nil` if the import of that module failed, and let the callback handle those cases, but I don't know how useful this is and it would probably make the callback logic more error-prone (a lot of potential null-pointer exceptions to handle).

**Comment by miversen33** [comment]
> Since the code in the callback requires both the modules it makes sense to me that import() only calls the callback if every module was succesfully imported, but it could mark their ImportStatus individually. For instance, if module1 exists but module2 doesn't, don't call the callback and set module1.imported = true and module2.imported = false.

This is where my head was going but I wanted to be sure that is how you were thinking as well (given this is your request)

> Alternatively, import() could set the input parameter to the callback function to nil if the import of that module failed, and let the callback handle those cases, but I don't know how useful this is and it would probably make the callback logic more error-prone (a lot of potential null-pointer exceptions to handle).

Right, and I'm not looking to break the main feature is import (reduction of error prone imports).

I don't hate this idea. I'm quite busy lately, I'll look to proof something out next week/next weekend and I'll toss it into a branch for you to try out and give feedback on.

Sound good @melkster ?

**Comment by mawkler** [comment]
@miversen33 Great! Thank you!
