### ISSUE TITLE
Should netman be a plugin requirement?

### ISSUE THREAD

**Issue by mawkler** [miversen33/import.nvim#12]
It isn't explicitly mentioned as a requirement (at least I interpreted its mention in the README only as an example of how to use import.nvim), but netman is [used here](https://github.com/miversen33/import.nvim/blob/main/lua/import/ui.lua#L212). Is this intentional? If netman is intented to be a requirement I think that could be clarified in the README :)

Edit: Also, netman doesn't seem to export a `.setup()`, so following the README in order to install it doesn't seem to work:
```lua
import('netman', function(netman)
    netman.setup({ "do module setup" })
end)
```

**Comment by miversen33** [comment]
Netman is not a requirement, just a fun little Easter egg for another project I am working on :)

**Comment by mawkler** [comment]
Ok, but netman is called by import.nvim right [here](https://github.com/miversen33/import.nvim/blob/main/lua/import/ui.lua#L212), so import.nvim will throw an error if netman isn't installed.

**Comment by miversen33** [comment]
Oh good catch! Ya that isn't supposed to be there, I was debugging an issue with the UI (I believe?). I'll get that removed quick

**Comment by miversen33** [comment]
@melkster I dont know if you were experiencing an error due to this, but if so can you see if you still are? I removed Netman from the source code (it was only in that one spot it looks like)

**Comment by mawkler** [comment]
Looks good to me :)

**Comment by miversen33** [comment]
Awesome sauce, closing this out
