### ISSUE TITLE
import() should return the loaded module(s)

### ISSUE THREAD

**Issue by dsully** [miversen33/import.nvim#19]
Just like `require` does.

Looks like it does so if there is a callback. It should also when there is no callback.

**Comment by miversen33** [comment]
[I explained a bit in this thread](https://github.com/miversen33/import.nvim/issues/10#issuecomment-1235544167) why `import` doesn't return the loaded module. In addition, adding this could break the the APIs ability to re-run a function on reload.

This was a conscious decision to enforce callbacks as that is how import protects the user on failed import.

If import returns the module on successful require, then what would it do on an unsuccessful require? The obvious answer (of return nil) means that you are giving up the safety that import provides.

**Comment by dsully** [comment]
Hey Mike - I had just assumed to do a `nil` check just like I would with `pcall`.

Perhaps a note in the README explaining this would be helpful for future readers.

**Comment by miversen33** [comment]
I believe this is called out [in the readme for the import function](https://github.com/miversen33/import.nvim#importimport)
Would you recommend it being worded differently or placed elsewhere?

**Comment by miversen33** [comment]
Closing this out. If there is a request for updated documentation, please open a new issue :)
